# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sinatra", "~> 4.1"

gem "rackup", "~> 2.2"

gem "sqlite3", "~> 2.5"

gem "sinatra-activerecord", "~> 2.0"

gem "rake", "~> 13.2"

gem "activerecord", "~> 7.2"

gem "sinatra-reloader", "~> 1.0"

gem "rainbow", "~> 3.1"
